# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_order_review.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderReview(object):
    def setupUi(self, OrderReview):
        OrderReview.setObjectName("OrderReview")
        OrderReview.resize(371, 341)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(OrderReview)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_orderDetail = QtWidgets.QTextBrowser(OrderReview)
        self.textBrowser_orderDetail.setObjectName("textBrowser_orderDetail")
        self.verticalLayout.addWidget(self.textBrowser_orderDetail)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Send = QtWidgets.QPushButton(OrderReview)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.horizontalLayout.addWidget(self.pushButton_Send)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_Cancel = QtWidgets.QPushButton(OrderReview)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(OrderReview)
        QtCore.QMetaObject.connectSlotsByName(OrderReview)

    def retranslateUi(self, OrderReview):
        _translate = QtCore.QCoreApplication.translate
        OrderReview.setWindowTitle(_translate("OrderReview", "Order Review"))
        self.pushButton_Send.setText(_translate("OrderReview", "Send"))
        self.pushButton_Cancel.setText(_translate("OrderReview", "Cancel"))
